// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Ggn8X-t5_HnnjZQvAKCguzsi95ZDhno',
    appId: '1:1006707074449:android:969b8ae2907adab9c72630',
    messagingSenderId: '1006707074449',
    projectId: 'helloflutter-687df',
    storageBucket: 'helloflutter-687df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLrgDz49XSduG_DQWq9CAoGY0RA5aawM',
    appId: '1:1006707074449:ios:01b4656dc7b11ddcc72630',
    messagingSenderId: '1006707074449',
    projectId: 'helloflutter-687df',
    storageBucket: 'helloflutter-687df.firebasestorage.app',
    androidClientId: '1006707074449-292smqlaov6k5uqv5b6kgjed711q6bji.apps.googleusercontent.com',
    iosClientId: '1006707074449-tf847cv9la6e635ohdvcrfpe83hsjcpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.laptrinhdidong',
  );
}
